version: "3.0"

services:
    web:
        restart: always
        build: ./web
        environment:
            - FLASK_DEBUG=1
            - FLASK_APP=/app/siiifu.py
        expose:
            - 5000
        #ports:
        #    - 5000:5000
        volumes:
            - ./web:/app
            - cache-volume:/data/cache
        #command: flask run --host 0.0.0.0
        command: /usr/local/bin/gunicorn -k gevent --reload --pythonpath /app --workers 2 --timeout 300 -b :5000 siiifu:app


    worker:
        restart: always
        build: ./web
        environment:
            - FLASK_DEBUG=1
            - FLASK_APP=/app/image.py
        expose:
            - 5000
        ports:
            - 5001:5000
        volumes:
            - ./web:/app
            - cache-volume:/data/cache
        #command: flask run --host 0.0.0.0
        command: /usr/local/bin/gunicorn -k gevent --reload --pythonpath /app --workers 2 --timeout 300 -b :5000 image:app


    nginx:
        restart: always
        image: nginx
        expose:
            - 8080
        ports:
            - 8081:8080
        volumes:
            - ./etc/default.conf:/etc/nginx/conf.d/default.conf
            - ./web/static:/www/static
            - cache-volume:/data/cache
        links:
            - web:web

volumes:
    cache-volume:

