version: "3.5"

services:
    siiifu:
        restart: always
        build: ./web
        expose:
            - 5000
        volumes:
            - ./web:/app
            - cache-volume:/data/cache
        command: /usr/local/bin/gunicorn -k gevent --reload --pythonpath /app --workers 5 --timeout 300 -b :5000 siiifu:app

    worker:
        restart: always
        build: ./web
        expose:
            - 5000
        volumes:
            - ./web:/app
            - cache-volume:/data/cache
        command: /usr/local/bin/gunicorn -k gevent --reload --pythonpath /app --workers 5 --timeout 300 -b :5000 image:app


    siiifu-front:
        restart: always
        image: nginx
        expose:
            - 8080
        ports:
            - 8081:8080
        volumes:
            - ./etc/default.conf:/etc/nginx/conf.d/default.conf
            - ./web/static:/www/static
            - cache-volume:/data/cache


volumes:
    cache-volume:


networks:
    default:
        name: siiifu
        driver: bridge

