version: "3.0"

services:
    web:
        restart: always
        build: ./web
        environment:
            - FLASK_DEBUG=1
            - FLASK_APP=/app/siiifu.py
        expose:
            - 5000
        ports:
            - 5000:5000
        volumes:
            - ./web:/app
        command: flask run --host 0.0.0.0


    nginx:
        restart: always
        build: ./nginx/
        expose:
            - 8080
        ports:
            - 8080:8080
        volumes:
            - ./web/static:/www/static
        links:
            - web:web

