version: "3.0"

services:
    web:
        environment:
            - FLASK_DEBUG=1
            - FLASK_APP=/app/siiifu.py
        command: flask run --host 0.0.0.0
        ports:
            - 5000:5000
        volumes:
            - ./web:/app

