version: "3.0"

services:
    web:
        environment:
            - FLASK_DEBUG=0
            - FLASK_APP=/app/siiifu.py
        command: /usr/local/bin/gunicorn --pythonpath /app -b :5000 siiifu:app
        ports:
            - 5000:5000

